docs: describe the release workflow in the contributing guide
xing/hops pull request #1697
Opened 2021-03-29 13:55 UTC by ZauberNerd

<details>
<summary>Bors merge bot cheat sheet</summary>

We are using [bors-ng](https://github.com/bors-ng/bors-ng) to automate merging of our pull requests. The following table provides a summary of commands that are available to reviewers (members of this repository with push access) and delegates (in case of `bors delegate+` or `bors delegate=[list]`).

| Syntax | Description |
| --- | --- |
| bors merge | Run the test suite and push to master if it passes. Short for "reviewed: looks good." |
| bors merge- | Cancel an r+, r=, merge, or merge= |
| bors try | Run the test suite without pushing to master. |
| bors try- | Cancel a try |
| bors delegate+ | Allow the pull request author to merge their changes. |
| bors delegate=[list] | Allow the listed users to r+ this pull request's changes. |
| bors retry | Run the previous command a second time. |

This is a short collection of opinionated commands. For a full list of the commands read the [bors reference](https://bors.tech/documentation/).

</details>

2021-03-29 14:00 UTC, herschel666 requested changes

2021-03-29 14:00 UTC, herschel666 commented on CONTRIBUTING.md
> +Each PR must have at least one release label, indicating which version it targets (":package: master", ":package: v14", etc..). Once the PR has been merged the release-bot will try to cherry-pick it
```diff
- to cherry-pick it into the respective release branch
+ to cherry-pick it onto the respective release branch
```

2021-03-29 14:08 UTC, ZauberNerd commented on CONTRIBUTING.md
> +Each PR must have at least one release label, indicating which version it targets (":package: master", ":package: v14", etc..). Once the PR has been merged the release-bot will try to cherry-pick it
Thanks, updated.

2021-03-29 14:44 UTC, ZauberNerd commented
bors merge

2021-04-07 07:59 UTC, ZauberNerd commented
bors retry

2021-04-07 08:08 UTC, merged